date_ranges:
  - start: "2023-07-25"
    end: "2023-08-13"
    closest_time: "12:00:00"
  # - start: "2023-02-01"
  #   end: "2023-02-10"
  #   closest_time: "13:00:00"  # Example of a different time than noon