date_range:
  - start: "2024-01-01"
    end: "2024-12-31"
    closest_time: "12:00:00"
    UTC_offset: "-04:00"
  # - start: "2023-02-01"
  #   end: "2023-02-10"
  #   closest_time: "13:00:00"  # Example of a different time than noon